#line 2 "src/lex.yy.c"

#line 4 "src/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[472] =
    {   0,
       28,   28,   32,   30,   28,   29,   27,   30,   26,   28,
       29,   27,   27,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   26,   26,   27,
       27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   26,   25,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
        0,    0,    0,    0,   19,    0,    0,    0,    0,    0,
        0,   12,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   16,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,   16,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    7,   15,
        0,    0,    0,    0,    0,    0,    8,    7,   15,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    0,
        0,    6,    0,    0,    0,   13,    0,    0,    0,    0,
       14,    0,    0,    0,    0,    0,    5,    9,    0,    0,

        5,   10,    0,    0,    0,    0,   23,    0,   23,    0,
        0,   21,   22,    0,    3,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    2,
        0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   11,   12,
       13,   12,   14,   12,   12,   15,   16,   17,    1,   18,
       19,   20,   21,    1,   22,   23,   24,   25,   26,   27,
       23,   23,   28,   23,   23,   29,   30,   23,   31,   32,
       23,   33,   34,   35,   36,   37,   23,   23,   23,   23,
        1,    1,    1,    1,   38,    1,   39,   23,   40,   41,

       42,   43,   44,   23,   45,   23,   23,   46,   47,   48,
       49,   50,   23,   51,   52,   53,   54,   55,   23,   56,
       57,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    1,    2,    1,    3,    1,    3,    4,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    5,
        4,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst flex_uint16_t yy_base[480] =
    {   0,
        0,   38,  885,  886,  882,  880,   16,   68,  878,  879,
      877,   17,   52,   28,  115,  823,    0,  829,  825,   28,
       38,   49,  834,  823,  823,  824,  833,  867,  866,   70,
      115,  849,  125,   50,   52,   81,   71,   73,   55,   54,
       87,   70,   74,  821,  847,   95,   58,   91,  102,    5,
       88,  113,  120,  117,  128,  129,  131,  126,  862,  886,
      134,    6,  135,  138,  139,  155,  141,  144,  156,  157,
      162,  164,  172,  168,  170,  169,  819,  886,   53,  173,
      175,  174,  176,  179,  180,  181,  182,  187,  177,  185,
      192,  860,  200,  194,  199,  201,  203,  205,  208,  211,

      213,  214,  220,  216,  218,  223,  859,  225,  224,  226,
      228,  231,  229,  230,  232,  233,  254,  239,  238,  244,
      858,  256,  255,  245,  265,  240,  276,  247,  257,  260,
      274,  284,  277,  283,  278,  806,  285,  286,  287,  294,
      295,  293,  290,  297,  298,  300,  302,  307,  303,  316,
      315,  317,  320,  318,  331,  321,  324,  325,  326,  330,
      337,  328,  340,  342,  343,  344,  351,  352,  353,  360,
      818,  355,  356,  358,  362,  364,  361,  372,  368,  369,
      376,  378,  379,  384,  385,  388,  391,  387,  395,  399,
      396,  401,  398,  402,  403,  808,  404,  406,  405,  411,

      417,  838,  414,  423,  415,  420,  422,  837,  424,  425,
      431,  430,  434,  436,  836,  442,  437,  444,  445,  447,
      835,  448,  802,  449,  450,  453,  455,  458,  886,  460,
      465,  461,  468,  467,  886,  469,  471,  472,  470,  473,
      480,  886,  489,  482,  485,  487,  490,  886,  491,  808,
      492,  832,  493,  494,  505,  500,  502,  506,  512,  831,
      507,  509,  830,  514,  515,  527,  523,  525,  524,  526,
      829,  528,  799,  530,  886,  539,  537,  540,  538,  544,
      546,  547,  886,  548,  553,  886,  556,  555,  558,  557,
      561,  564,  565,  886,  568,  799,  567,  571,  572,  574,

      580,  583,  575,  578,  585,  588,  589,  590,  591,  594,
      598,  595,  601,  596,  827,  605,  609,  608,  610,  611,
      612,  616,  617,  619,  622,  620,  627,  628,  630,  636,
      631,  632,  634,  840,  639,  638,  641,  649,  824,  823,
      822,  651,  637,  644,  654,  653,  661,  821,  820,  819,
      659,  646,  827,  658,  668,  660,  817,  886,  886,  886,
      670,  674,  675,  677,  676,  816,  886,  886,  886,  683,
      684,  827,  814,  685,  686,  886,  688,  690,  813,  692,
      693,  886,  689,  694,  822,  886,  811,  810,  700,  697,
      886,  809,  808,  702,  701,  822,  886,  886,  703,  806,

      886,  886,  705,  805,  722,  804,  886,  803,  886,  780,
      801,  886,  886,  772,  886,  779,  769,  776,  771,  767,
      770,  794,  807,  704,  777,  775,  756,  777,  780,  763,
      798,  797,  796,  787,  786,  785,  784,  793,  792,  782,
      791,  772,  776,  739,  768,  780,  733,  886,  772,  738,
      766,  722,  748,  725,  737,  717,  886,  709,  704,  703,
      707,  729,  739,  684,  695,  684,  728,  710,  707,  886,
      886,  758,  268,  761,  766,  772,  778,  783,  788
    } ;

static yyconst flex_int16_t yy_def[480] =
    {   0,
      472,  472,  471,  471,  471,  471,  473,  474,  475,  471,
      471,  471,  471,  473,  476,  471,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  478,  475,  471,
      471,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  471,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  478,  471,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  471,  471,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  479,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  471,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      479,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  471,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      471,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  471,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  471,  477,  477,  477,  477,  477,  471,  477,
      477,  477,  477,  477,  471,  477,  476,  476,  476,  476,
      476,  471,  476,  476,  476,  476,  476,  471,  476,  471,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  471,  477,  471,  477,  477,  477,  477,  477,
      477,  477,  471,  477,  476,  471,  476,  476,  476,  476,
      476,  476,  476,  471,  476,  471,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  471,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  471,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  471,  477,  477,  477,  477,  471,  471,  471,
      477,  477,  476,  476,  476,  476,  471,  471,  471,  476,
      476,  471,  477,  477,  477,  471,  477,  477,  476,  476,
      476,  471,  476,  476,  471,  471,  477,  477,  477,  477,
      471,  476,  476,  476,  476,  471,  471,  471,  477,  477,

      471,  471,  476,  476,  471,  477,  471,  476,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
        0,  471,  471,  471,  471,  471,  471,  471,  471
    } ;

static yyconst flex_uint16_t yy_nxt[944] =
    {   0,
        4,    5,    6,    4,    4,    4,    4,    4,    4,    7,
        7,    7,    7,    7,    7,    7,    4,    8,    4,    4,
        4,   12,   12,   13,   78,   60,   30,   30,   30,   30,
       30,   30,   30,   12,   83,   13,   68,    4,    4,    5,
        6,    4,    4,    4,    4,    4,    4,    7,    7,    7,
        7,    7,    7,    7,    4,    8,    4,    4,    4,   13,
       48,   31,   31,   31,   31,   31,   31,   31,   50,   60,
       52,   60,   78,   60,   60,    4,   15,   78,   49,   30,
       30,   30,   30,   30,   30,   30,   51,   53,   16,   60,
       60,   18,   60,   60,   70,   19,   72,  108,   64,   20,

       60,   68,   21,   65,   22,   73,   60,   78,   23,   80,
       78,   71,   76,   66,   78,   24,   81,   25,   75,   69,
       26,   78,   27,   33,   31,   31,   31,   31,   31,   31,
       31,   67,   78,   33,   84,   79,   78,   74,   34,   78,
       88,   85,   35,   82,   60,   78,   36,   78,   78,   37,
       78,   38,   35,   60,   60,   39,   61,   60,   60,   62,
       60,   38,   40,   60,   41,   86,   66,   42,   87,   43,
       89,   91,   63,   98,   60,   60,   60,   90,   94,   43,
       96,   60,   97,   60,  103,  100,   93,   60,   60,   60,
       95,   60,   78,   78,   78,   78,   78,  112,   78,   78,

       78,   78,   99,  117,   78,  109,   78,  101,  110,  104,
      114,   78,  122,   60,  106,  102,  105,  113,   60,   60,
       60,  116,   60,  119,   60,  111,  127,   60,  118,  115,
       60,  124,   60,   60,  125,   60,  132,   60,  123,   60,
      120,  129,   60,   78,   78,   78,  128,   78,   78,   78,
       78,   78,   78,  131,  126,  141,  134,   78,   78,   60,
      139,  130,  143,   78,   60,  138,   60,  133,  137,  142,
       14,  135,  155,   78,   60,   60,   60,  146,  153,   60,
      140,  147,  144,  145,   60,  148,  157,  161,  149,  162,
      150,  152,  159,   60,  154,   60,   60,   60,  156,  158,

      160,  151,   60,   60,   78,   78,   78,   34,  174,   78,
      163,   35,   78,   78,   78,  165,   78,   78,  166,   78,
      167,   78,   78,  169,  164,  176,   78,  178,  170,  168,
      179,   40,  175,  172,   78,   78,   78,   78,  173,   78,
       60,  177,  180,   60,   60,   60,  186,   60,   46,   60,
       60,   51,  183,   47,   53,  181,   60,   49,   35,   60,
      188,   60,   60,   60,  187,  190,   55,  167,  182,  184,
       60,   60,   60,  191,   78,   78,  185,   78,   63,   60,
       78,   78,  199,   78,  197,  189,  192,   78,   78,   71,
      193,   78,   69,   67,  195,   78,  201,   78,   78,  203,

      198,  194,  200,   60,   60,  204,   60,   60,  206,  205,
       60,  202,  212,  210,   60,   60,  207,   60,   60,  214,
       60,   60,   60,   78,   78,   78,  216,  209,  208,  211,
       78,  213,  217,   78,   78,  226,   78,  218,  220,   78,
      219,   78,   78,   78,   60,  215,  225,  230,  231,   60,
       60,  222,  221,   60,  228,   60,   60,  224,  233,  227,
      239,   60,  244,   60,   60,  232,   60,   60,   78,   78,
      234,  238,   78,  241,   78,  243,  236,   78,  237,   78,
       78,  255,  240,  246,   78,  253,   78,   78,   78,   60,
       60,   60,   60,  256,  245,  247,  251,  257,  252,   60,

      249,   60,  264,  266,   60,  254,   60,  261,   60,   60,
       60,   78,   78,   78,  268,  258,  259,  260,  262,   78,
      263,   78,  267,  265,   78,   78,   78,  277,   60,  272,
      276,   78,  278,   60,   60,  270,  274,  279,  280,  269,
      271,  282,   60,   60,   60,   60,   60,   60,  288,   78,
      281,  287,  284,  285,  289,  293,   78,   78,   78,   78,
      290,  291,  298,   78,  300,   78,   78,   78,  292,  297,
      301,  302,   60,  295,   60,   60,   60,   60,  299,  307,
       60,  305,  309,   60,   60,  303,   78,   60,  311,  310,
       78,   78,  306,   78,   78,  319,  308,   78,  317,   78,

      304,  314,   78,  312,   78,  320,  321,   60,   60,   60,
       60,  316,  328,   60,   60,   60,  326,   60,  313,  329,
       60,  330,  318,  322,   78,  323,  324,   78,   78,   78,
       78,   78,  325,  336,  338,   78,   78,  333,   78,   60,
      327,   60,  340,  331,  345,  339,   60,   60,  332,   60,
       60,   60,  347,   60,  335,   60,   78,   78,   78,  355,
       78,  342,  337,   60,  348,   60,  349,  341,   78,  343,
       78,  344,   60,   60,  357,  364,  351,   78,   60,   78,
       60,  346,  350,  354,  352,  356,  366,   78,  363,   78,
      361,  362,  374,   78,   60,   60,   60,  365,  370,  375,

      371,  380,   60,   60,   78,   78,  373,   78,   60,   78,
      387,   60,   60,   60,  377,  381,   78,  392,  378,   78,
       60,   60,   78,  379,   60,  410,  470,  383,  384,  390,
      469,  425,  468,  395,  388,  467,  466,  389,  394,  426,
      465,  393,  411,  464,  399,  400,  403,  463,  462,  404,
      461,  406,  460,  408,  459,  458,  457,  427,    9,    9,
        9,    9,    9,    9,   17,  456,   17,   29,  455,  454,
      453,   29,   32,   32,   32,   32,  452,   32,   45,   45,
       45,   45,  451,   45,   59,  450,  449,  448,   59,  121,
      447,  446,  445,  121,  444,  443,  442,  441,  440,  439,

      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  409,  407,  405,  402,  401,  398,
      397,  396,  391,  386,  385,  382,  376,  372,  369,  368,
      367,  360,  359,  358,  353,  334,  315,  296,  294,  286,
      283,  275,  273,  250,  248,  242,  235,  229,  223,  196,
      171,  471,  136,   92,  107,   92,   78,   77,   60,   28,
       28,   58,   57,   56,   55,   54,   47,   46,   44,   11,
       10,   28,   11,   10,  471,    3,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471
    } ;

static yyconst flex_int16_t yy_chk[944] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,   12,    7,   50,   62,   12,   12,   12,   12,
       12,   12,   12,   14,   50,   14,   62,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   13,
       20,   13,   13,   13,   13,   13,   13,   13,   21,   34,
       22,   35,   79,   40,   39,    2,    8,   47,   20,   30,
       30,   30,   30,   30,   30,   30,   21,   22,    8,   42,
       37,    8,   38,   43,   38,    8,   39,   79,   34,    8,

       36,   37,    8,   35,    8,   40,   41,   51,    8,   47,
       48,   38,   43,   36,   46,    8,   48,    8,   42,   37,
        8,   49,    8,   15,   31,   31,   31,   31,   31,   31,
       31,   36,   52,   33,   51,   46,   54,   41,   15,   53,
       55,   52,   15,   49,   33,   58,   15,   55,   56,   15,
       57,   15,   33,   61,   63,   15,   33,   64,   65,   33,
       67,   33,   15,   68,   15,   53,   61,   15,   54,   15,
       56,   58,   33,   68,   66,   69,   70,   57,   64,   33,
       66,   71,   67,   72,   73,   70,   63,   74,   76,   75,
       65,   73,   80,   82,   81,   83,   89,   83,   84,   85,

       86,   87,   69,   88,   90,   80,   88,   71,   81,   74,
       85,   91,   93,   94,   76,   72,   75,   84,   95,   93,
       96,   87,   97,   90,   98,   82,   98,   99,   89,   86,
      100,   95,  101,  102,   96,  104,  103,  105,   94,  103,
       91,  100,  106,  109,  108,  110,   99,  111,  113,  114,
      112,  115,  116,  102,   97,  112,  105,  119,  118,  126,
      110,  101,  114,  120,  124,  109,  128,  104,  108,  113,
      473,  106,  122,  117,  123,  122,  129,  117,  119,  130,
      111,  117,  115,  116,  125,  117,  124,  128,  117,  129,
      117,  118,  126,  131,  120,  127,  133,  135,  123,  125,

      127,  117,  134,  132,  137,  138,  139,  132,  139,  143,
      130,  132,  142,  140,  141,  132,  144,  145,  132,  146,
      132,  147,  149,  134,  131,  141,  148,  143,  135,  133,
      144,  132,  140,  137,  151,  150,  152,  154,  138,  153,
      156,  142,  145,  157,  158,  159,  158,  162,  146,  160,
      155,  149,  154,  147,  150,  152,  161,  148,  155,  163,
      160,  164,  165,  166,  159,  162,  151,  155,  153,  156,
      167,  168,  169,  163,  172,  173,  157,  174,  155,  170,
      177,  175,  174,  176,  172,  161,  164,  179,  180,  167,
      168,  178,  166,  165,  170,  181,  176,  182,  183,  178,

      173,  169,  175,  184,  185,  178,  188,  186,  180,  179,
      187,  177,  186,  184,  189,  191,  181,  193,  190,  188,
      192,  194,  195,  197,  199,  198,  190,  183,  182,  185,
      200,  187,  190,  203,  205,  199,  201,  191,  193,  206,
      192,  207,  204,  209,  210,  189,  198,  203,  204,  212,
      211,  195,  194,  213,  201,  214,  217,  197,  206,  200,
      212,  216,  217,  218,  219,  205,  220,  222,  224,  225,
      207,  211,  226,  214,  227,  216,  209,  228,  210,  230,
      232,  228,  213,  219,  231,  226,  234,  233,  236,  239,
      237,  238,  240,  230,  218,  220,  224,  231,  225,  241,

      222,  244,  239,  241,  245,  227,  246,  236,  243,  247,
      249,  251,  253,  254,  244,  232,  233,  234,  237,  256,
      238,  257,  243,  240,  255,  258,  261,  254,  262,  249,
      253,  259,  255,  264,  265,  246,  251,  256,  257,  245,
      247,  259,  267,  269,  268,  270,  266,  272,  265,  274,
      258,  264,  261,  262,  266,  270,  277,  279,  276,  278,
      267,  268,  276,  280,  278,  281,  282,  284,  269,  274,
      279,  280,  285,  272,  288,  287,  290,  289,  277,  287,
      291,  284,  289,  292,  293,  281,  297,  295,  291,  290,
      298,  299,  285,  300,  303,  300,  288,  304,  298,  301,

      282,  295,  302,  292,  305,  301,  302,  306,  307,  308,
      309,  297,  309,  310,  312,  314,  307,  311,  293,  310,
      313,  311,  299,  303,  316,  304,  305,  318,  317,  319,
      320,  321,  306,  317,  319,  322,  323,  314,  324,  326,
      308,  325,  321,  312,  326,  320,  327,  328,  313,  329,
      331,  332,  328,  333,  316,  330,  343,  336,  335,  336,
      337,  323,  318,  344,  329,  352,  330,  322,  338,  324,
      342,  325,  346,  345,  338,  345,  332,  354,  351,  356,
      347,  327,  331,  335,  333,  337,  347,  355,  344,  361,
      342,  343,  355,  362,  363,  365,  364,  346,  351,  356,

      352,  364,  370,  371,  374,  375,  354,  377,  383,  378,
      374,  380,  381,  384,  361,  365,  390,  380,  362,  389,
      395,  394,  399,  363,  403,  405,  469,  370,  371,  378,
      468,  424,  467,  384,  375,  466,  465,  377,  383,  424,
      464,  381,  405,  463,  389,  390,  394,  462,  461,  395,
      460,  399,  459,  403,  458,  456,  455,  424,  472,  472,
      472,  472,  472,  472,  474,  454,  474,  475,  453,  452,
      451,  475,  476,  476,  476,  476,  450,  476,  477,  477,
      477,  477,  449,  477,  478,  447,  446,  445,  478,  479,
      444,  443,  442,  479,  441,  440,  439,  438,  437,  436,

      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  423,  422,  421,  420,  419,  418,  417,  416,  414,
      411,  410,  408,  406,  404,  400,  396,  393,  392,  388,
      387,  385,  379,  373,  372,  366,  357,  353,  350,  349,
      348,  341,  340,  339,  334,  315,  296,  273,  271,  263,
      260,  252,  250,  223,  221,  215,  208,  202,  196,  171,
      136,  121,  107,   92,   77,   59,   45,   44,   32,   29,
       28,   27,   26,   25,   24,   23,   19,   18,   16,   11,
       10,    9,    6,    5,    3,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/main.l"
/* Nome: Mariane Tiemi Iguti RA: 147279 
   EA876 -Trabalho 01 */
#line 4 "src/main.l"

#include <stdlib.h>
#include <string.h>

void yyerror(char *);
#include "y.tab.h"

#line 840 "src/lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 15 "src/main.l"


#line 1061 "src/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 472 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 886 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 "src/main.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "src/main.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "src/main.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "src/main.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "src/main.l"
{ return BELEM_PRESTADOR_TAG; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "src/main.l"
{ return BELEM_TOMADOR_TAG; }   
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "src/main.l"
{ return BELEM_SERVICO_TAG; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "src/main.l"
{ return BELEM_ISS_TAG; }  
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "src/main.l"
{ printf("tag p:%s\n", yytext);return CORUMBA_JOAOMON_PRESTADOR_ABRETAG; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "src/main.l"
{ printf("tag p:%s\n", yytext);return CORUMBA_JOAOMON_PRESTADOR_FECHATAG; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "src/main.l"
{ printf("tag t:%s\n", yytext);return CORUMBA_JOAOMON_GERADOR_ABRETAG; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "src/main.l"
{ printf("tag t:%s\n", yytext);return CORUMBA_JOAOMON_GERADOR_FECHATAG; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "src/main.l"
{ printf("tag c:%s\n", yytext);return CORUMBA_JOAOMON_CODIGO_ABRETAG; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "src/main.l"
{ printf("tag c:%s\n", yytext);return CORUMBA_JOAOMON_CODIGO_FECHATAG; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "src/main.l"
{ return CORUMBA_JOAOMON_SERVICO_TAG; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "src/main.l"
{return CORUMBA_JOAOMON_ISS_TAG; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "src/main.l"
{return SAOLUIS_PRESTADOR_ABRETAG;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "src/main.l"
{return SAOLUIS_PRESTADOR_FECHATAG;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "src/main.l"
{return SAOLUIS_GERADOR_ABRETAG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "src/main.l"
{return SAOLUIS_GERADOR_FECHATAG;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "src/main.l"
{return SAOLUIS_MUNICIPIO_ABRETAG;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "src/main.l"
{return SAOLUIS_MUNICIPIO_FECHATAG;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "src/main.l"
{ return SAOLUIS_SERVICO_TAG; }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 59 "src/main.l"
{ printf("abre:%s\n", yytext);
                yylval.string = strdup(yytext); 
                return ABRETAG;
              }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 64 "src/main.l"
{ printf("fecha:%s\n", yytext);return FECHATAG; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "src/main.l"
{// printf("string:%s\n", yytext);
                                        yylval.string = strdup(yytext);
                                        return STRING;
                                    }                                                     
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "src/main.l"
{ 
                                        int i; int size = strlen(yytext); 
                                        for(i = 0; i < size; i++)
                                        { 
                                            if(yytext[i] == ',')
                                                yytext[i] = '.';    
                                        }
                                        yylval.number= atof(yytext);
                                       //printf("numero:%.2f\n", yylval.number);
                                        return NUMERO;

                                      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "src/main.l"
;                                                                   
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 84 "src/main.l"
;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "src/main.l"
;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "src/main.l"
ECHO;
	YY_BREAK
#line 1293 "src/lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 472 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 472 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 471);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 87 "src/main.l"



int yywrap() 
{  
  return 1;
}

